on: workflow_dispatch

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew build

      - run: |
          ./gradlew jreleaserConfig
          ./gradlew clean
          ./gradlew publish
          ./gradlew jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - run: ./gradlew :gradle-plugin:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
