on: workflow_dispatch

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew build
      - run: ./gradlew publishAllPublicationsToProjectLocalRepository \
             zipMavenCentralPortalPublication \
             releaseMavenCentralPortalPublication
        env:
          MAVEN_CENTRAL_PORTAL_USERNAME: ${{ secrets.USERNAME }}
          MAVEN_CENTRAL_PORTAL_PASSWORD: ${{ secrets.PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SECRET_KEY }}

      - run: ./gradlew :gradle-plugin:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
